[package]
name = "deface"
version = "0.1.0"
authors = ["Michael <Michael@LAZEAR-WORK>"]
repository = "https://github.com/lazear/deface.git"
homepage = "https://github.com/lazear/deface"
license = "MIT"
readme = "README.md"

[profile.release]
lto = true

[dependencies]
